"""empty message

Revision ID: 0a32175718cc
Revises: fc58ffa80b77
Create Date: 2022-08-31 01:54:37.038945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a32175718cc'
down_revision = 'fc58ffa80b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('post_tags_tag_id_fkey', 'post_tags', type_='foreignkey')
    op.drop_constraint('post_tags_post_id_fkey', 'post_tags', type_='foreignkey')
    op.create_foreign_key(None, 'post_tags', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(None, 'post_tags', 'tags', ['tag_id'], ['id'])
    op.drop_column('post_tags', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_tags', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'post_tags', type_='foreignkey')
    op.drop_constraint(None, 'post_tags', type_='foreignkey')
    op.create_foreign_key('post_tags_post_id_fkey', 'post_tags', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('post_tags_tag_id_fkey', 'post_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.drop_table('post_tag')
    # ### end Alembic commands ###
