"""empty message

Revision ID: 03ecdd6bbc9e
Revises: 2eda7121b760
Create Date: 2022-08-03 10:35:49.009304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03ecdd6bbc9e'
down_revision = '2eda7121b760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_tag_id_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'tag_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('posts_tag_id_fkey', 'posts', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
