"""empty message

Revision ID: 49af871d7fa0
Revises: 907b764087cc
Create Date: 2022-08-19 23:58:49.337349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49af871d7fa0'
down_revision = '907b764087cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], )
    )
    op.drop_table('follows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('followed_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], name='follows_followed_id_fkey'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name='follows_follower_id_fkey')
    )
    op.drop_table('followers')
    # ### end Alembic commands ###
