"""empty message

Revision ID: dfa273d1d402
Revises: 03ecdd6bbc9e
Create Date: 2022-08-10 09:31:12.002238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfa273d1d402'
down_revision = '03ecdd6bbc9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic')
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('profile_pic', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
