"""empty message

Revision ID: f0c2f75e7052
Revises: 3f6f75d869ff
Create Date: 2022-09-23 23:14:52.288189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c2f75e7052'
down_revision = '3f6f75d869ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('profile_picture', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_picture')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
