"""empty message

Revision ID: fbd0f4443bb2
Revises: 
Create Date: 2022-08-30 18:54:13.793095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbd0f4443bb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('tag', sa.Integer(), nullable=False))
    op.drop_column('tags', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('name', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('tags', 'tag')
    # ### end Alembic commands ###
