"""empty message

Revision ID: fc58ffa80b77
Revises: 3f6f75d869ff
Create Date: 2022-08-30 22:49:08.783793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc58ffa80b77'
down_revision = '3f6f75d869ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_tags_tag_id_fkey', 'post_tags', type_='foreignkey')
    op.drop_constraint('post_tags_post_id_fkey', 'post_tags', type_='foreignkey')
    op.create_foreign_key(None, 'post_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'post_tags', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_tags', type_='foreignkey')
    op.drop_constraint(None, 'post_tags', type_='foreignkey')
    op.create_foreign_key('post_tags_post_id_fkey', 'post_tags', 'posts', ['post_id'], ['id'])
    op.create_foreign_key('post_tags_tag_id_fkey', 'post_tags', 'tags', ['tag_id'], ['id'])
    # ### end Alembic commands ###
